# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main
        run: |
          pwd
          chmod +x autorun.sh
          ./autorun.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch1.sh
          ./autorunch1.sh
          
      - name: Main
        run: |
          pwd
          chmod +x autorunch2.sh
          ./autorunch2.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch3.sh
          ./autorunch3.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch4.sh
          ./autorunch4.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch5.sh
          ./autorunch5.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch6.sh
          ./autorunch6.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch7.sh
          ./autorunch7.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch8.sh
          ./autorunch8.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch9.sh
          ./autorunch9.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch10.sh
          ./autorunch10.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch11.sh
          ./autorunch11.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch12.sh
          ./autorunch12.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch13.sh
          ./autorunch13.sh

      - name: Main
        run: |
          pwd
          chmod +x autorunch14.sh
          ./autorunch14.sh

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push
